// Real local demonstration: two registered guest-style test accounts, real Judge0, persisted result.
// Generated source is known from this controlled fixture; the similarity check does not infer AI authorship.
const path = require('node:path');
const fs = require('node:fs');
const { randomUUID, randomBytes } = require('node:crypto');
const { io } = require('../client/node_modules/socket.io-client');
const readline = require('node:readline');
const root = path.resolve(__dirname, '..');
const base = 'http://localhost:5000';
const suffix = randomUUID().slice(0, 8);
const password = randomBytes(24).toString('base64url');
const sockets = [];
const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
const source = {
  'Two Sum': `// Controlled demonstration: generated by Codex for this test match.
const fs = require('fs');
function findPair(values, target) {
    const seen = new Map();
    for (let index = 0; index < values.length; index++) {
        const value = values[index];
        const complement = target - value;
        if (seen.has(complement)) {
            return [seen.get(complement), index];
        }
        if (!seen.has(value)) {
            seen.set(value, index);
        }
    }
    return null;
}
const input = fs.readFileSync(0, 'utf8').trim();
if (input.length > 0) {
    const numbers = input.split(/\\s+/).map(Number);
    const count = numbers[0];
    const target = numbers[1];
    const result = findPair(numbers.slice(2, count + 2), target);
    if (result !== null) {
        console.log(result[0] + ' ' + result[1]);
    }
}
`,
  'Balanced Brackets': `// Controlled demonstration: generated by Codex for this test match.
const input = require('fs').readFileSync(0, 'utf8').trim();
const stack = [];
const opening = new Set(['(', '[', '{']);
const partner = { ')': '(', ']': '[', '}': '{' };
let valid = true;
for (const character of input) {
    if (opening.has(character)) {
        stack.push(character);
    } else if (stack.length === 0 || stack.pop() !== partner[character]) {
        valid = false;
        break;
    }
}
console.log(valid && stack.length === 0 ? 'true' : 'false');
`,
};
async function api(route, token, body) {
  const response = await fetch(base + route, { ...(body ? { method: 'POST', body: JSON.stringify(body) } : {}), headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, signal: AbortSignal.timeout(15000) });
  const data = await response.json(); if (!response.ok) throw new Error(data.error || String(response.status)); return data;
}
async function main() {
  const accounts = [];
  for (const label of ['Aurora', 'Vector']) {
    const account = { username: `Guest${label}_${suffix}`, email: `guest-${label.toLowerCase()}-${suffix}@example.test`, password };
    accounts.push({ ...account, auth: await api('/api/auth/register', null, account) });
  }
  for (const account of accounts) {
    const socket = io(base, { auth: { token: account.auth.token }, transports: ['websocket'], reconnection: false }); sockets.push(socket);
    await new Promise((resolve, reject) => { socket.once('connect', resolve); socket.once('connect_error', reject); });
  }
  const found = new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error('No match found')), 15000); sockets[0].once('match_found', match => { clearTimeout(timer); resolve(match); }); });
  sockets[0].emit('join_queue'); sockets[1].emit('join_queue'); const match = await found;
  const fixture = { matchId: match.roomId, url: `http://127.0.0.1:5173/battle/${match.roomId}`, accounts: accounts.map(({ auth, ...account }) => ({ ...account, id: auth.user.id })), source, problems: match.problems.map(p => ({ id: p.id, title: p.title })), generatedBy: 'Codex; controlled simulation, not inferred by a detector' };
  fs.mkdirSync(path.join(root, '.cache'), { recursive: true }); fs.writeFileSync(path.join(root, '.cache/battle-demo.json'), JSON.stringify(fixture, null, 2));
  async function submit(account, problem, code, mode = 'submissions') {
    const saved = await api(`/api/matches/${match.roomId}/${mode}`, account.auth.token, { problemId: problem.id, language: 'javascript', sourceCode: code, requestId: randomUUID() });
    for (let i = 0; i < 220; i++) {
      const detail = await api(`/api/submissions/${saved.id}`, account.auth.token);
      if (detail.state === 'FINISHED') {
        console.log(`${account.username} / ${problem.title} / ${mode}: ${detail.verdict}, ${detail.passed}/${detail.total}`);
        return detail;
      }
      await wait(500);
    }
    throw new Error('Judging timed out');
  }
  let prepared = false, finished = false;
  async function prepare() {
    if (prepared) return;
    const sum = match.problems.find(p => p.title === 'Two Sum');
    const brackets = match.problems.find(p => p.title === 'Balanced Brackets');
    const a = await submit(accounts[0], sum, source[sum.title]);
    const b = await submit(accounts[1], sum, source[sum.title]);
    if (a.verdict !== 'ACCEPTED' || b.verdict !== 'ACCEPTED' || b.integrity?.state !== 'review_suggested') throw new Error('Expected accepted solutions and a real similarity flag');
    fixture.flaggedSubmissionId = b.id; fixture.integrity = b.integrity;
    await submit(accounts[1], brackets, "// Controlled incorrect solution\nconsole.log('false');");
    prepared = true; fs.writeFileSync(path.join(root, '.cache/battle-demo.json'), JSON.stringify(fixture, null, 2));
    console.log('READY CODING SCREEN: both 1/2 solved; GuestVector has a real high-overlap advisory. AI assessment is not_assessed.');
  }
  async function finish() {
    if (finished) return; await prepare();
    const brackets = match.problems.find(p => p.title === 'Balanced Brackets');
    const last = await submit(accounts[0], brackets, source[brackets.title]);
    if (last.verdict !== 'ACCEPTED') throw new Error('Winner solution was not accepted');
    let snapshot; for (let i = 0; i < 30; i++) { snapshot = await api(`/api/matches/${match.roomId}`, accounts[0].auth.token); if (snapshot.result) break; await wait(300); }
    if (snapshot.result?.outcome !== 'win' || snapshot.result.ratingChanges[accounts[0].auth.user.id] !== 16 || snapshot.progress[accounts[1].auth.user.id].solved !== 1) throw new Error('Unexpected persisted result');
    const report = await api('/api/integrity/reports', accounts[0].auth.token, { submissionId: fixture.flaggedSubmissionId, category: 'SUSPECTED_AI', details: 'CONTROLLED DEMO: this solution was generated by Codex for the simulation. Its source matches the opponent reference. This is test provenance, not a detector authorship claim; do not sanction a real account from this fixture.' });
    const standing = await api('/api/integrity/standing', accounts[1].auth.token);
    if (standing.strikes !== 0 || standing.banned) throw new Error('A pending report must never automatically ban');
    fixture.result = snapshot.result; fixture.report = report; fixture.standing = standing;
    fs.writeFileSync(path.join(root, '.cache/battle-demo.json'), JSON.stringify(fixture, null, 2));
    finished = true; console.log('PASS: Aurora wins 2–1; Elo 1216 (+16) / 1184 (−16). Report pending; Vector 0 strikes and unbanned. Result saved on main localhost.');
  }
  console.log(`READY ${fixture.url}; guest login details in .cache/battle-demo.json. Commands: prepare, finish, stop`);
  const input = readline.createInterface({ input: process.stdin }); let busy = false;
  input.on('line', async command => { if (busy) return; busy = true; try { if (command.trim() === 'prepare') await prepare(); if (command.trim() === 'finish') await finish(); if (command.trim() === 'stop') { for (const socket of sockets) socket.disconnect(); input.close(); process.exit(0); } } catch (e) { console.error('FAIL', e.message); } finally { busy = false; } });
  process.on('SIGINT', () => { for (const socket of sockets) socket.disconnect(); process.exit(); });
}
main().catch(e => { for (const socket of sockets) socket.disconnect(); console.error(e.message); process.exitCode = 1; });
